@host = localhost:3333

### Subscribe to event
POST http://{{host}}/subscriptions
Content-Type: application/json

{
  "name": "User", //Usuario que será cadastrado
  "email": "user@devstage.team", //E-mail
  "referrer": "1cbbb6e3-4a0e-4acb-89e3-bd65d1a9abff" // ID do usuário que indicou
}

### Access invite link
GET http://{{host}}/invites/0fd5dc41-bd53-452e-929e-405461189e86

### Get subscriber invites clicks
GET http://{{host}}/subscribers/0fd5dc41-bd53-452e-929e-405461189e86/ranking/clicks

### Get subscriber invites count
GET http://{{host}}/subscribers/0fd5dc41-bd53-452e-929e-405461189e86/ranking/count

### Get subscriber ranking position
GET http://{{host}}/subscribers/0fd5dc41-bd53-452e-929e-405461189e86/ranking/position

### Get ranking
GET http://{{host}}/ranking
