@host = localhost:3333

### Subscribe to event
POST http://{{host}}/subscriptions
Content-Type: application/json

{
  "name": "Usuario convidado",
  "email": "usuario.convidado@gmail.com",
  "referrer": "83f43dbf-45cc-4b5d-a102-eacbfdc58e45"
}

### Access invite link
GET http://{{host}}/invites/83f43dbf-45cc-4b5d-a102-eacbfdc58e45

### Get subscriber invites clicks
GET http://{{host}}/subscribers/83f43dbf-45cc-4b5d-a102-eacbfdc58e45/ranking/clicks

### Get subscriber invites count
GET http://{{host}}/subscribers/83f43dbf-45cc-4b5d-a102-eacbfdc58e45/ranking/count

### Get subscriber ranking position
GET http://{{host}}/subscribers/83f43dbf-45cc-4b5d-a102-eacbfdc58e45/ranking/position

### Get ranking
GET http://{{host}}/ranking

### Message to be executed on the PostgreSQL database

POST http://{{host}}/messages
Content-Type: application/json

{
  "message": "Quantos inscritos possuem e-mails com dominio @gmail.com?"
}

### Message to be executed on the Redis database

POST http://{{host}}/messages
Content-Type: application/json

{
  "message": "Me diga o nome do usuário com maior número de pontuação no ranking!"
}